// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv87-ArpQlSBBaODWmbZ0MoaHyHIQjvW0',
    appId: '1:172921807692:web:7efcbdce301905edaf65e9',
    messagingSenderId: '172921807692',
    projectId: 'jolary-212pp',
    authDomain: 'jolary-212pp.firebaseapp.com',
    storageBucket: 'jolary-212pp.firebasestorage.app',
    measurementId: 'G-EYZSKMDZR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRX083RWkhmLLm30_M4yunUG9FeEvNWPM',
    appId: '1:172921807692:android:0243a61c8f3a0aa6af65e9',
    messagingSenderId: '172921807692',
    projectId: 'jolary-212pp',
    storageBucket: 'jolary-212pp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIUT4KWjCSRD0xeKaBFfWOAyTAJaE6Qkc',
    appId: '1:172921807692:ios:e3f61239749b069faf65e9',
    messagingSenderId: '172921807692',
    projectId: 'jolary-212pp',
    storageBucket: 'jolary-212pp.firebasestorage.app',
    iosBundleId: 'com.example.nova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIUT4KWjCSRD0xeKaBFfWOAyTAJaE6Qkc',
    appId: '1:172921807692:ios:e3f61239749b069faf65e9',
    messagingSenderId: '172921807692',
    projectId: 'jolary-212pp',
    storageBucket: 'jolary-212pp.firebasestorage.app',
    iosBundleId: 'com.example.nova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDv87-ArpQlSBBaODWmbZ0MoaHyHIQjvW0',
    appId: '1:172921807692:web:c60f345f90abb214af65e9',
    messagingSenderId: '172921807692',
    projectId: 'jolary-212pp',
    authDomain: 'jolary-212pp.firebaseapp.com',
    storageBucket: 'jolary-212pp.firebasestorage.app',
    measurementId: 'G-6SDTHMTL85',
  );

}